//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeInfoEntities : DbContext
    {
        public EmployeeInfoEntities()
            : base("name=EmployeeInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmploymentHistory> EmploymentHistories { get; set; }
        public virtual DbSet<Institute> Institutes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
    }


    public class Details
    {
        public IEnumerable<Employee> Employees { get; set; }

        public IEnumerable<EmploymentHistory> EmploymentHistories { get; set; }

        public IEnumerable<Certificate> Certificates { get; set; }

        public IEnumerable<Department> Departments { get; set; }

        public IEnumerable<Institute> Institutes { get; set; }

        public IEnumerable<Job> Jobs { get; set; }

    }
}
